### ISSUE TITLE
Data Description

### ISSUE THREAD

**Issue by tranminhtu258** [tranminhtu258/dsproject2#1]
[Andrew to have the description]

**Comment by Bargwan** [comment]
The study area will be defined by the boundary on this map:
![image](https://user-images.githubusercontent.com/17022878/29550037-c2037078-874a-11e7-806a-be4e7e9996c9.png)
Peter is asking the client for a vector representation of this boundary (although we might be able to find it ourselves somewhere on SARIG.  When we receive it, **we'll need code to create a subset of all drill holes targeting minerals which are situated within the boundary**.

We can then provide a statistic on the success/failure rate of drillholes in our study area.

**Comment by Bargwan** [comment]
As mentioned on Hangout - we'll request this csv direct from the client.  The SARIG website limits download to 1,000 drill holes at a time.
